### ISSUE TITLE
update comment not working

### ISSUE THREAD

**Issue by ethanryan** [hashicorp/nextjs-bundle-analysis#57]
update comment is not working, example:

<img width="922" alt="update-comment-not-working" src="https://user-images.githubusercontent.com/8107812/233730636-747526dd-773e-48d4-aba7-5271975102f4.png">

this is causing multiple comments to appear with each new commit, instead of new commits replacing old comments.

see related issue: https://github.com/hashicorp/nextjs-bundle-analysis/issues/56

**Comment by ethanryan** [comment]
fixed this issue with solution offered in this closed issue: https://github.com/hashicorp/nextjs-bundle-analysis/issues/52#issuecomment-1507644855

> You can upgrade right now by replacing the Find, Create, and Update steps with the following:
> ```
> - name: Comment
>   uses: marocchino/sticky-pull-request-comment@v2
>   with:
>     header: next-touched-pages
>     message: ${{ steps.get-comment-body.outputs.body }}
> ```

may be helpful to keep this issue open for others facing this problem, until this PR fixing the issue is merged: https://github.com/hashicorp/nextjs-bundle-analysis/pull/54

**Comment by isBatak** [comment]
@ethanryan you can just update this line https://github.com/hashicorp/nextjs-bundle-analysis/blob/a4cf35f98ec1ecb5753ba966acde342fbd175319/template.yml#L113 and append you project name form `package.json` prefixed with `_`
For example:
```json
// package.json
{
	"name": "my-app",
	...
}
```
```yaml
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE_my-app -->'
```
e.g. `'<!-- __NEXTJS_BUNDLE_${PROJECT_NAME} -->'`
